spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountsDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          min-partition-count: 3
      output-bindings: ACCOUNT_CREATED
      bindings:
        bank-out-0:
          destination: ACCOUNT_CREATED
          content-type: application/json


logging:
  level:
    org.springframework.cloud.stream: DEBUG

server:
  port: 4000




